server:
  port: 8085
maxFetchResult: 30
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      #      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.ddl-auto: create-drop
      # modify batch size as necessary
      #      hibernate.jdbc.batch_size: 25
      #      hibernate.order_inserts: true
      #      hibernate.order_updates: true
      #      hibernate.query.fail_on_pagination_over_collection_fetch: true
      #      hibernate.query.in_clause_parameter_padding: true
      hibernate:
#        dialect: org.hibernate.dialect.MariaDB103Dialect
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: demo
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
jwt:
  secret: shiki_oris
host:
  frontend:
    account:
      resetPassword: http://localhost:3000/reset-password/
logging:
  level:
    org.springframework.web.socket: TRACE
graphql:
  servlet:
    cors:
      allow-credentials: true
      allowed-headers:
        - Authorization
        - Content-Type
        - X-Requested-With
        - X-CSRF-Token
        - Access-Control-Allow-Origin
        - Content-Type
        - Cache-Control
      allowed-origins: http://localhost:3000, http://192.168.1.44:3000, http://192.168.72.101:3000
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    async:
      timeout: 50000